### ISSUE TITLE
I think your demon regex overflowed my editor's regex buffer

### ISSUE THREAD

**Issue by ghost** [Tegmen/RegEx-BrainF-Interpreter#1]
Probably wontfix.

**Comment by Tegmen** [comment]
That doesn't surprise me. What Program/ Editor did you use?  What was your Input (Brainfuck Program)?

**Comment by ghost** [comment]
I tried the hello world program provided in Atom. It stopped parsing the Find regex after ~205 characters and declared it an invalid regular expression. It works perfectly fine (if you can manage to keep mashing Replace All without breaking anything) in Notepad++, though.

**Comment by Tegmen** [comment]
That sounds to me like a bug in Atom, not my RegEx

**Comment by ghost** [comment]
I don't believe it's a bug at all. I think Atom just doesn't like 1K regexes. :P
